### ISSUE TITLE
Expose both pipeline phase and step type from PipelineExecutionStepState

### ISSUE THREAD

**Issue by kwin** [adobe/aio-lib-java-cloudmanager#18]
To be able to visualize a progress log, it would be nice to expose both the action (including optional details) as well as the phase label from https://github.com/adobe/aio-lib-java-cloudmanager/blob/main/src/main/java/io/adobe/cloudmanager/model/PipelineExecutionStepState.java to be able to replicate the visualization in the Cloud Manager UI.

Example phase label = "Build and Code Scanning"
Example action/step label = "Code Scanning"

If you don't want to to expose labels for i18n reasons maybe an enum type for both step and phase can be exposed via get methods.

**Comment by bstopp** [comment]
The StepState's action is available through the API already, [here](https://opensource.adobe.com/aio-lib-java-cloudmanager/apidocs/io/adobe/cloudmanager/swagger/model/PipelineExecutionStepState.html#getAction()). It is part of the generated class after Lombok has processed the source. Translating the value from the API to a meaningful message would be the responsibility of the caller..

The Pipeline also contains a [list of the available phases](https://opensource.adobe.com/aio-lib-java-cloudmanager/apidocs/io/adobe/cloudmanager/swagger/model/Pipeline.html#getPhases()), including their IDs which are referenced in the StepStates. This should provide the necessary information to translate the state/enum into a meaningful message.

**Comment by kwin** [comment]
@bstopp Thanks for the answer, but the phase id is actually not exposed in https://opensource.adobe.com/aio-lib-java-cloudmanager/apidocs/io/adobe/cloudmanager/swagger/model/PipelinePhase.html, therefore a mapping is currently not possible...

**Comment by bstopp** [comment]
Ah - if the PhaseId isn't in the API - that's a topic for the CloudManager API docs project. We can only expose what is provided by the API.
