### ISSUE TITLE
Expose getDelegate for non-serializable wrappers around Swagger models

### ISSUE THREAD

**Issue by kwin** [adobe/aio-lib-java-cloudmanager#24]
Although all Swagger model classes are serializable the wrapper classes in `io.adobe.cloudmanager.model` are not. E.g. `PipelineExecutionStepState` contains a reference towards `CloudManagerApi` which is not serializable. For all those wrapper classes the delegate should be exposed via a public `getDelegate()` method,  because otherwise consumers cannot get hold of the serializable model instance.

**Comment by bstopp** [comment]
The classes in the the package `io.adobe.cloudmanager.model` all extend from their Swagger delegate classes, so they are serializable. Though, the `serialVersionUID` was miswing and is now added via #28.

The lombok `@Delegate` annotation exposes _all_ of the public methods from the delegate class, therefore there should be no reason to ever access the Delegate object itself. Adding the serialVersionUID should solve any persistence issues.

**Comment by kwin** [comment]
This won't work, as the field `client` (https://github.com/adobe/aio-lib-java-cloudmanager/blob/1ac71fba9023f953e63ad5bcf0ee4fda2e3c5dca/src/main/java/io/adobe/cloudmanager/model/PipelineExecutionStepState.java#L44) is still not serializable!
